### PR TITLE
Update comment to reflect the current (MIT) license on the code.

### PR DESCRIPTION
**Pull request by cpressey**
Thanks for hosting this program.

I was a bit confused after first reading the source code and seeing the comment at the top suggesting it's GPL'ed code, but then seeing GitHub list the license as MIT.

After looking around a bit I realised it's been relicensed.  It seems that it's simply that the two lines in the code referring to the GPL did not get updated when that happened.

So, I've opened this pull request to correct that, and hopefully make it a little less confusing for other readers of the code.

(Incidentally, I think it would also be entirely appropriate to mention the historical copyright status in the LICENSE file itself, i.e. to change the 3rd line of LICENSE to something like `Copyright (c) 2002 Raph Levien, (c) 2019 David A. Wheeler`.  However, that is much less of a source of confusion, and is a change I do not feel comfortable with making myself -- so I have not made it part of this PR. I only note it here as my opinion.)

### CODE REVIEW

**Comment by benjub** [comment]
I would merge this PR, but I'm not sure what to do with the proposal to change `LICENSE`. @tirix ? @david-a-wheeler ?

**Comment by tirix** [comment]
I see David has stored [a mail](https://github.com/david-a-wheeler/mmverify.py/blob/master/relicense.txt) from @raphlinus in this repo, where Raph states he owns the copyright. I'm not sure if this is meant to be restrictive (in the sense that no one else does), or permissive (in the sense that he has the right to do what he wants with the SW, including giving these rights to David).

So to me, this PR looks reasonable, and Raph expressed he would have used MIT, but I'm not sure about the change in `LICENSE` either. 

Raph is currently busy with very interesting projects like Xilem, I'm not sure he has time for this!
David is the more versed into Free and Open Source Software so he might have an expert's opinion.

**Comment by david-a-wheeler** [comment]
Thanks for noting the confusion!!

Yes, Raph was the original copyright holder so he has the right to relicense it. He relicensed it to MIT, and it's clearly documented in LICENSE as being MIT license, as well as in the embedded email. The text in the source code is no longer correct, so this commit fixes it.

So I'm going to merge this change now. Thanks for the fix!!

**Comment by tirix** [comment]
@david-a-wheeler what about the other changed mentioned in OP, but not in this PR?

> change the 3rd line of LICENSE to something like Copyright (c) 2002 Raph Levien, (c) 2019 David A. Wheeler.

**Pull request merged**
